name: build-and-test
on: [ push ]
integrations: [ artifactory-enablers-kms ]

vars:
  - sigstore-kms-ovhcloud

jobs:
  build:
    runs-on: KMSAAS/stash_ovh_net/cen/kmsaas-cds-workers/kms-base-go
    steps:
      - uses: actions/checkout
        id: checkout
      - id: lint
        run: make lint
      - id: build
        run: make build
      - uses: actions/uploadArtifact
        with:
          path: build/sigstore-kms-ovhcloud

  integration-test:
    runs-on: KMSAAS/stash_ovh_net/cen/kmsaas-cds-workers/kms-base-go
    needs:
      - build
    steps:
      - uses: actions/checkout
        id: checkout

      - id: setup-credentials
        run: |-
          #!/bin/bash
          set -e
          cat > $PWD/cert.pem <<EOF
          ${{vars.sigstore-kms-ovhcloud.KMS_HTTP_CERT}}
          EOF
          cat > $PWD/key.pem <<EOF
          ${{vars.sigstore-kms-ovhcloud.KMS_HTTP_KEY}}
          EOF
          chmod 600 $PWD/cert.pem $PWD/key.pem

      - id: integration-test
        run: |-
          #!/bin/bash
          set -e
          export KMS_INTEGRATION_KEY_ID="${{vars.sigstore-kms-ovhcloud.KMS_INTEGRATION_KEY_ID}}"
          export KMS_HTTP_ENDPOINT="${{vars.sigstore-kms-ovhcloud.KMS_HTTP_ENDPOINT}}"
          export KMS_HTTP_ID="${{vars.sigstore-kms-ovhcloud.KMS_HTTP_OKMSID}}"
          export KMS_HTTP_CERT="$PWD/cert.pem"
          export KMS_HTTP_KEY="$PWD/key.pem"
          trap 'rm -f $PWD/cert.pem $PWD/key.pem' EXIT
          make integration-test

      - uses: actions/uploadArtifact
        with:
          path: build/integration-junit.xml
      - uses: actions/uploadArtifact
        with:
          path: build/integration-coverage.html
      - uses: actions/uploadArtifact
        with:
          path: build/integration-coverage.out
      - uses: actions/uploadArtifact
        with:
          path: build/integration-test-results.json
